import Head from 'next/head'
import Main from '../components/main';
import Navbar from '../components/navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Polygon GUILD</title>
        <meta name="description" content="Generated by next app"/>
        <link rel="icon" href="Vector.svg"/>
      </Head>
      <Main/>
    </div>
  );
}
